### ISSUE TITLE
Fix Azure pipelines build fails with the new 2020 update

### ISSUE THREAD

**Issue by CJBuchel** [CurtinFRC/2020-InfiniteRecharge#34] opened 2020-01-28 15:39 UTC

**Comment by Finchiedev** [comment] 2020-01-29 03:45
Nathan and I found that the problem is with `-Pno-roborio`, which was fixed by removing all options & only installing the toolchain then clean building. The source code is [here](https://github.com/UWA-FRC/2020-InfiniteRecharge/blob/master/azure-pipelines.yml) if you'd like to take a look

**Closed as completed** 2020-01-29 06:21 UTC
Labels: bug
